//! Declarative Dockerfile builder for `Snapshots::create` (docs/protocol.md section 3a
//! "Snapshots"). String concatenation, byte-identical to the Python and TypeScript builders:
//! a snapshot build is a one-shot server-side step, nothing here needs parsing back.

use base64::{engine::general_purpose::STANDARD, Engine};

/// Single-quotes `s` for a POSIX shell, escaping embedded quotes.
fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn quoted(pkgs: &[&str]) -> String {
    pkgs.iter().map(|p| sh_quote(p)).collect::<Vec<_>>().join(" ")
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Image {
    lines: Vec<String>,
}

impl Image {
    pub fn base(image: &str) -> Image {
        Image { lines: vec![format!("FROM {image}")] }
    }

    pub fn run(mut self, cmd: &str) -> Image {
        self.lines.push(format!("RUN {cmd}"));
        self
    }

    pub fn workdir(mut self, dir: &str) -> Image {
        self.lines.push(format!("WORKDIR {dir}"));
        self
    }

    /// One `ENV K="v"` line per entry, in iteration order (pass a slice or `Vec` of pairs to
    /// control it; a `BTreeMap` iterates sorted).
    pub fn env<K: AsRef<str>, V: AsRef<str>>(mut self, vars: impl IntoIterator<Item = (K, V)>) -> Image {
        for (k, v) in vars {
            self.lines.push(format!("ENV {}=\"{}\"", k.as_ref(), v.as_ref()));
        }
        self
    }

    pub fn pip_install(mut self, pkgs: &[&str]) -> Image {
        if !pkgs.is_empty() {
            self.lines.push(format!("RUN pip install --no-cache-dir {}", quoted(pkgs)));
        }
        self
    }

    pub fn npm_install(mut self, pkgs: &[&str]) -> Image {
        if !pkgs.is_empty() {
            self.lines.push(format!("RUN npm install -g {}", quoted(pkgs)));
        }
        self
    }

    /// Writes `content` to `dest` in the image. A Dockerfile COPY needs a build-context file
    /// that does not exist here, so the content is embedded as base64 and decoded in a RUN step.
    pub fn copy_text(mut self, dest: &str, content: &str) -> Image {
        let d = sh_quote(dest);
        let b64 = sh_quote(&STANDARD.encode(content));
        self.lines.push(format!("RUN mkdir -p \"$(dirname {d})\" && echo {b64} | base64 -d > {d}"));
        self
    }

    pub fn to_dockerfile(&self) -> String {
        self.lines.join("\n") + "\n"
    }
}

impl std::fmt::Display for Image {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.to_dockerfile())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by running the Python `Image` with the same calls (tests/fixtures/image.Dockerfile):
    ///
    /// ```text
    /// Image.base("python:3.12-slim").run("apt-get update").workdir("/work")
    ///   .env({"A": "1", "B": "two words"}).pip_install(["requests", "it's"]).pip_install([])
    ///   .npm_install(["left-pad"]).copy_text("/etc/app/conf.txt", "hello 'world'\nünï")
    /// ```
    #[test]
    fn matches_the_python_builder_byte_for_byte() {
        let img = Image::base("python:3.12-slim")
            .run("apt-get update")
            .workdir("/work")
            .env([("A", "1"), ("B", "two words")])
            .pip_install(&["requests", "it's"])
            .pip_install(&[])
            .npm_install(&["left-pad"])
            .copy_text("/etc/app/conf.txt", "hello 'world'\nünï");
        assert_eq!(img.to_dockerfile(), include_str!("../tests/fixtures/image.Dockerfile"));
        assert_eq!(img.to_string(), img.to_dockerfile());
    }
}
