import { StrictMode, useCallback, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter } from "react-router-dom";
import { Theme } from "@astryxdesign/core/theme";
import { LayerProvider } from "@astryxdesign/core/Layer";

// Astryx ships its own reset + base layer. Order matters: reset first, then
// the pre-compiled theme (generated by `npm run theme` from src/theme.ts),
// then our handful of app-level rules.
import "@astryxdesign/core/reset.css";
import "@astryxdesign/core/astryx.css";
import "./theme.built.css";
import "./app.css";

import App from "./App";
// Pre-built theme object: static token map, no runtime HCT colour math in the
// bundle. Regenerate with `npm run theme` after editing src/theme.ts.
import { sandboxTheme } from "./theme";
import { readMode, writeMode, type Mode } from "./theme";
import { ModeContext } from "./mode";

const qc = new QueryClient({
  defaultOptions: {
    queries: { retry: 1, refetchOnWindowFocus: false, staleTime: 10_000 },
  },
});

function Root() {
  const [mode, setMode] = useState<Mode>(() => readMode());

  const toggle = useCallback(() => {
    setMode((m) => {
      const next: Mode = m === "dark" ? "light" : "dark";
      writeMode(next);
      return next;
    });
  }, []);

  const ctx = useMemo(() => ({ mode, toggle }), [mode, toggle]);

  return (
    <QueryClientProvider client={qc}>
      <Theme theme={sandboxTheme} mode={mode}>
        {/* LayerProvider owns the toast viewport + overlay stacking context. */}
        <LayerProvider>
          <ModeContext value={ctx}>
            <BrowserRouter>
              <App />
            </BrowserRouter>
          </ModeContext>
        </LayerProvider>
      </Theme>
    </QueryClientProvider>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <Root />
  </StrictMode>,
);
